ConnectionString:
    SqlServer: "Server=${SqlServer.Host},${SqlServer.Port};Database=${SqlServer.Database};User Id=${SqlServer.Username};Password=${SqlServer.Password};"
    Redis: "${Redis.Host}:${Redis.Port},password=${Redis.Password},ssl=False,abortConnect=False,defaultDatabase=${Redis.DefaultDatabase},instanceName=${Redis.InstanceName}"
    Cassandra: "host=${Cassandra.Host};port=${Cassandra.Port};user=${Cassandra.Username};password=${Cassandra.Password};keyspace=${Cassandra.KeySpace};ssl=false"
